name: 'Validate STACKIT Database ACLs'
description: 'A github action that uses the STACKIT API to ensure that database ACLs only allow the cluster to connect to the database instances.'
inputs:
  organisation_id:
    description: 'The Organisation ID, to validate all Databases in your STACKIT organisation.'
    required: true

runs:
  using: 'composite'
  steps:
    - run: echo "INSTALL PYTHON"
      shell: bash
    - name: "Install Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ${{ github.action_path }}/.python-version
    - run: echo "INSTALL UV"
      shell: bash
    - name: "Install uv"
      uses: astral-sh/setup-uv@v6
      with:
        working-directory: ${{ github.action_path }}
    - run: echo "RUN script"
      shell: bash
    - name: "Validate STACKIT Database ACLs"
      run:  uv run ${{ github.action_path }}/src/main.py validate-org ${{ inputs.organisation_id }}
      shell: bash