name: 'Validate STACKIT Database ACLs'
description: 'A github action that uses the STACKIT API to ensure that database ACLs only allow the cluster to connect to the database instances.'
inputs:
  organisation_id:
    description: 'The Organisation ID, to validate all Databases in your STACKIT organisation.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: "Install Python"
      uses: actions/setup-python@v5
    - name: "Install uv"
      uses: astral-sh/setup-uv@v6
    - name: "Validate STACKIT Database ACLs"
      run:  uv run src/main.py validate-org ${{ inputs.organisation_id }}
      shell: bash